# Generated by Django 3.0.3 on 2020-05-20 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profilePic', models.ImageField(blank=True, default='default_profile_pic.png', upload_to='')),
                ('username', models.ForeignKey(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
