# Generated by Django 3.0.3 on 2020-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=20)),
                ('followed', models.CharField(max_length=20)),
                ('following', models.IntegerField()),
            ],
        ),
    ]
