# Generated by Django 3.0.3 on 2020-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='slug',
            field=models.SlugField(default='invalid-url'),
        ),
    ]
