# Generated by Django 3.0.3 on 2020-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_profiledata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='slug',
            field=models.CharField(default='invalid-url', max_length=40),
        ),
    ]
