# Generated by Django 3.0.3 on 2020-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20200523_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='slug',
            field=models.SlugField(default='invalid-url'),
        ),
    ]
